import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';
import prettier from 'eslint-config-prettier';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Generated by `vitest run --coverage` (now the default via
    // `coverage.enabled: true`, vitest.config.ts) — not source, and
    // gitignored, but this override list replaces eslint-config-next's own
    // defaults rather than extending them, so it needs restating here too.
    'coverage/**',
  ]),
]);

export default eslintConfig;
