import { z } from 'zod';
import { notificationCategorySchema } from './enums';

/**
 * The fixed set of mutations that fan out into a real notification, per the
 * Stage 4 Checkpoint 4 scoping decision: every audit-logged mutation
 * CLAUDE.md's Requirement 5 (or §4.2/§4.3) explicitly calls out as a
 * broadcast trigger. Settings changes, invite generation (as opposed to
 * acceptance), team bootstrap, and collection-point CRUD are deliberately
 * excluded — see the Stage 4 Checkpoint 4 Progress note in PLAN.md. The five
 * `swap_*` types (Checkpoint 7, CLAUDE.md §3.4/Requirement 4) were added
 * later, following the same "every lifecycle transition broadcasts" rule.
 * `shift_reminder` (Checkpoint 9, CLAUDE.md §3.11) is different in kind from
 * every other type here — system-generated by a `ScheduledTask` firing, not
 * a direct consequence of a user action, and `self`-scoped to one recipient
 * rather than team-broadcast — but goes through the exact same outbox pipe.
 * `member_added_directly` (CLAUDE.md §4.2's admin-direct-creation path) was
 * added 2026-08-20 after it turned out the API had emitted this eventType
 * since that feature shipped without ever adding it here — every row of
 * that type failed this schema, which the SSE stream tolerates (it skips
 * and logs an unparseable row rather than dropping the whole connection —
 * see notifications.ts's `sendRow`) but the plain list `GET` did not, so a
 * team member simply loading /notifications could get a hard 500 whenever
 * any row in their history had this eventType.
 */
export const notificationEventTypeSchema = z.enum([
  'shift_claimed',
  'shift_released',
  'session_updated',
  'session_cancelled',
  'session_point_players_updated',
  'schedule_template_created',
  'schedule_template_updated',
  'member_promoted',
  'member_demoted',
  'member_removed',
  'member_added_directly',
  'invite_accepted',
  'swap_requested',
  'swap_accepted',
  'swap_declined',
  'swap_expired',
  'swap_cancelled',
  'shift_reminder',
]);
export type NotificationEventType = z.infer<typeof notificationEventTypeSchema>;

export const notificationSeveritySchema = z.enum(['normal', 'emergency']);
export type NotificationSeverity = z.infer<typeof notificationSeveritySchema>;

export const notificationSchema = z.object({
  id: z.string().uuid(),
  teamId: z.string().uuid(),
  eventType: notificationEventTypeSchema,
  category: notificationCategorySchema,
  severity: notificationSeveritySchema,
  payload: z.record(z.string(), z.unknown()),
  readAt: z.string().datetime().nullable(),
  dismissedAt: z.string().datetime().nullable(),
  createdAt: z.string().datetime(),
});
export type Notification = z.infer<typeof notificationSchema>;

export const notificationListResponseSchema = z.object({
  notifications: z.array(notificationSchema),
  nextCursor: z.string().uuid().nullable(),
  unreadCount: z.number().int(),
});
export type NotificationListResponse = z.infer<typeof notificationListResponseSchema>;

export const unreadNotificationCountResponseSchema = z.object({
  count: z.number().int(),
});
export type UnreadNotificationCountResponse = z.infer<typeof unreadNotificationCountResponseSchema>;
